# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nvcf-invocation-service.fullname" . }}
  namespace: {{ include "nvcf-invocation-service.namespace" . }}
  labels:
    {{- include "nvcf-invocation-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.invocation.replicaCount }}
  selector:
    matchLabels:
      {{- include "nvcf-invocation-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "nvcf-invocation-service.vaultAnnotations" . | nindent 8 }}
        {{- with .Values.invocation.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if or .Values.invocation.env .Values.invocation.metrics.enabled }}
        checksum/config-env: {{ dict "env" .Values.invocation.env "metrics" .Values.invocation.metrics "tracing" .Values.invocation.tracing | toYaml | sha256sum }}
        {{- end }}
      labels:
        {{- include "nvcf-invocation-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.invocation.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: invocation-api
      securityContext:
        {{- toYaml .Values.invocation.podSecurityContext | nindent 8 }}
      volumes:
        {{- with .Values.invocation.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.invocation.metrics.enabled }}
        - name: app-config
          configMap:
            name: {{ include "nvcf-invocation-service.fullname" . }}-env
            items:
              - key: APP_CONFIG_YAML
                path: settings.yaml
        {{- end }}
        - name: vault-config-templates
          configMap:
            name: {{ include "nvcf-invocation-service.fullname" . }}-vault-agent-tpl
            items:
              - key: secrets.json.tmpl
                path: secrets.json.tmpl
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.invocation.securityContext | nindent 12 }}
          image: "{{ include "nvcf-invocation-service.image" . }}"
          imagePullPolicy: {{ .Values.invocation.image.pullPolicy }}
          volumeMounts:
            {{- with .Values.invocation.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.invocation.metrics.enabled }}
            - name: app-config
              mountPath: /etc/nvcf-invocation
              readOnly: true
            {{- end }}
            - name: vault-config-templates
              mountPath: /vault/config/templates
              readOnly: true
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- if or .Values.invocation.env .Values.invocation.metrics.enabled }}
          envFrom:
            - configMapRef:
                name: {{ include "nvcf-invocation-service.fullname" . }}-env
          {{- end }}
          ports:
            {{- range .Values.invocation.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
            {{- end }}
            {{- if .Values.invocation.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.invocation.metrics.port }}
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.invocation.resources | nindent 12 }}
      {{- with .Values.invocation.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.invocation.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.invocation.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.invocation.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
