# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nv_api_keys.fullname" . }}
  namespace: {{ include "nv_api_keys.namespace" . }}
  labels:
    {{- include "nv_api_keys.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apikeys.replicaCount }}
  {{- with .Values.apikeys.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nv_api_keys.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "nv_api_keys.vaultAnnotations" . | nindent 8 }}
        {{- with .Values.apikeys.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.apikeys.env }}
        checksum/config-env: {{ toYaml .Values.apikeys.env | sha256sum }}
        {{- end }}
      labels:
        {{- include "nv_api_keys.labels" . | nindent 8 }}
        {{- with .Values.apikeys.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.apikeys.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: api-keys-api
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ include "nv_api_keys.image" . }}"
          imagePullPolicy: {{ .Values.apikeys.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.apikeys.service.port }}
              protocol: TCP
            - name: management-port
              containerPort: {{ .Values.apikeys.managementPort }}
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- if .Values.apikeys.env }}
          envFrom:
            - configMapRef:
                name: {{ include "nv_api_keys.fullname" . }}-env
          {{- end }}
          {{- with .Values.apikeys.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apikeys.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apikeys.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apikeys.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 1000
          volumeMounts:
            - name: vault-config-templates
              mountPath: /vault/config/templates
              readOnly: true
            - name: token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
            
      {{- with .Values.apikeys.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apikeys.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: vault-config-templates
          configMap:
            name: {{ include "nv_api_keys.fullname" . }}-vault-agent-tpl
            items:
              - key: secrets.json.tmpl
                path: secrets.json.tmpl
        - name: token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3600
                  audience: http://openbao-server.vault-system.svc.cluster.local:8200
